[package]
name = "matoscout-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zerotoprod"


[dependencies]
# tokio
tokio = { version = "1", features = ["full"] }

# http
axum = { version = "0.7.4", features = ["tracing"] }
tower-http = { version = "0.5", features = ["trace"] }

# db
sqlx = { version = "0.7.4", features = [
  "runtime-tokio-rustls",
  "macros",
  "postgres",
] }

# serde
serde = { version = "1", features = ["derive"] }

# tracing
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = { version = "0.2" }

# utils
config = { version = "0.14" }
secrecy = { version = "0.8", features = ["serde"] }
uuid = { version = "1.8", features = ["v4"] }

[dev-dependencies]
once_cell = { version = "1.19" }
reqwest = { version = "0.12" }
