application:
  port: 3000
  host: 0.0.0.0
jwt:
  secret: my-jwt-secret
  access_token_exp_milliseconds: 600000
  refresh_token_exp_milliseconds: 604800000
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  database_name: matoscout
